#!/usr/bin/env bash

cp node_modules/discovery-channel/index.js node_modules/discovery-channel/index.js.orig
cp node_modules/discovery-swarm/index.js node_modules/discovery-swarm/index.js.orig
cp node_modules/multicast-dns/index.js node_modules/multicast-dns/index.js.orig

cp patch/discovery-channel.js node_modules/discovery-channel/index.js 
cp patch/discovery-swarm.js node_modules/discovery-swarm/index.js 
cp patch/multicast-dns.js node_modules/multicast-dns/index.js 


